apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "app.fullname" . }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secretName }}
        objectType: secretsmanager
        jmesPath: 
          - path: DB_HOST
            objectAlias: DB_HOST
          - path: DB_PORT
            objectAlias: DB_PORT
          - path: DB_NAME
            objectAlias: DB_NAME
          - path: DB_USER
            objectAlias: DB_USER  
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD     
  secretObjects:
    - secretName: {{ include "app.fullname" . }}
      type: Opaque
      data:
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_PORT
          key: DB_PORT
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: DB_USER
          key: DB_USER
        - objectName: DB_PASSWORD
          key: DB_PASSWORD  