name: "Install Prerequisites"
description: "Install kubectl and Helm Utilities"
runs:
  using: "composite"
  
  steps:
    - name: 'Install kubectl'
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      shell: bash
    
    - name: 'Install Helm'
      run: |
        curl -LO https://git.io/get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh
      shell: bash


